/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Spider
 */
public class FormQuestions extends javax.swing.JFrame {

    /**
     * Creates new form FormQuestions
     */
    public FormQuestions() {
        initComponents();
        this.setTitle("Menú Principal");
        this.getContentPane().setBackground(Color.WHITE);
        Image ico = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Log.png"));
        this.setIconImage(ico);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadioButtomGroup = new javax.swing.ButtonGroup();
        PanelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnCap1 = new javax.swing.JButton();
        btnCap2 = new javax.swing.JButton();
        btnCap3 = new javax.swing.JButton();
        btnCap4 = new javax.swing.JButton();
        btnCap5 = new javax.swing.JButton();
        btnCap6 = new javax.swing.JButton();
        btnCap7 = new javax.swing.JButton();
        btnCap8 = new javax.swing.JButton();
        btnCap9 = new javax.swing.JButton();
        btnCap10 = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        PanelDeslice = new javax.swing.JPanel();
        labelUser = new javax.swing.JLabel();
        PanelHistorial = new javax.swing.JPanel();
        btnCerrarHistorial = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel12 = new javax.swing.JLabel();
        PanelPreguntas = new javax.swing.JPanel();
        SubPanel = new javax.swing.JTabbedPane();
        IniciarPregunta = new javax.swing.JPanel();
        numeroPregunta = new javax.swing.JLabel();
        Pregunta = new javax.swing.JLabel();
        PanelRecuerda = new javax.swing.JPanel();
        Recuerda = new javax.swing.JLabel();
        txtRespuesta = new javax.swing.JLabel();
        btnAceptarPizarra = new javax.swing.JButton();
        sumNota = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PanelOpciones = new javax.swing.JPanel();
        imagen1 = new javax.swing.JLabel();
        imagen2 = new javax.swing.JLabel();
        respuesta1 = new javax.swing.JRadioButton();
        respuesta2 = new javax.swing.JRadioButton();
        respuesta3 = new javax.swing.JRadioButton();
        respuesta4 = new javax.swing.JRadioButton();
        btnNextPregunta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Incorrecta = new javax.swing.JLabel();
        Correcta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tituloCap = new javax.swing.JLabel();
        PanelBotonesIndice = new javax.swing.JPanel();
        btnIndice = new javax.swing.JButton();
        btnAleatorio = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        FondoTotal = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 620));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMenu.setBackground(new java.awt.Color(184, 207, 229));
        PanelMenu.setMaximumSize(new java.awt.Dimension(220, 570));
        PanelMenu.setMinimumSize(new java.awt.Dimension(220, 570));
        PanelMenu.setPreferredSize(new java.awt.Dimension(220, 570));
        PanelMenu.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CAPÍTULOS");
        PanelMenu.add(jLabel1);
        jLabel1.setBounds(30, 0, 170, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book.jpg"))); // NOI18N
        PanelMenu.add(jLabel2);
        jLabel2.setBounds(50, 40, 130, 110);

        btnNext.setBackground(new java.awt.Color(255, 255, 255));
        btnNext.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNext.setText("SIGUIENTE CAPÍTULO");
        btnNext.setBorder(null);
        btnNext.setBorderPainted(false);
        btnNext.setFocusPainted(false);
        btnNext.setRequestFocusEnabled(false);
        PanelMenu.add(btnNext);
        btnNext.setBounds(20, 520, 180, 30);

        btnCap1.setBackground(new java.awt.Color(255, 255, 255));
        btnCap1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCap1.setText("CAPÍTULO 1");
        btnCap1.setBorder(null);
        btnCap1.setBorderPainted(false);
        btnCap1.setFocusPainted(false);
        PanelMenu.add(btnCap1);
        btnCap1.setBounds(10, 170, 200, 40);

        btnCap2.setBackground(new java.awt.Color(255, 255, 255));
        btnCap2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCap2.setText("CAPÍTULO 2");
        btnCap2.setBorder(null);
        btnCap2.setBorderPainted(false);
        btnCap2.setFocusPainted(false);
        btnCap2.setRequestFocusEnabled(false);
        PanelMenu.add(btnCap2);
        btnCap2.setBounds(10, 220, 200, 40);

        btnCap3.setBackground(new java.awt.Color(255, 255, 255));
        btnCap3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCap3.setText("CAPÍTULO 3");
        btnCap3.setBorder(null);
        btnCap3.setBorderPainted(false);
        btnCap3.setFocusPainted(false);
        btnCap3.setRequestFocusEnabled(false);
        PanelMenu.add(btnCap3);
        btnCap3.setBounds(10, 270, 200, 40);

        btnCap4.setBackground(new java.awt.Color(255, 255, 255));
        btnCap4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCap4.setText("CAPÍTULO 4");
        btnCap4.setBorder(null);
        btnCap4.setBorderPainted(false);
        btnCap4.setFocusPainted(false);
        btnCap4.setRequestFocusEnabled(false);
        PanelMenu.add(btnCap4);
        btnCap4.setBounds(10, 320, 200, 40);

        btnCap5.setBackground(new java.awt.Color(255, 255, 255));
        btnCap5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCap5.setText("CAPÍTULO 5");
        btnCap5.setBorder(null);
        btnCap5.setBorderPainted(false);
        btnCap5.setFocusPainted(false);
        btnCap5.setRequestFocusEnabled(false);
        PanelMenu.add(btnCap5);
        btnCap5.setBounds(10, 370, 200, 40);

        btnCap6.setBackground(new java.awt.Color(255, 255, 255));
        btnCap6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCap6.setText("CAPÍTULO 6");
        btnCap6.setBorder(null);
        btnCap6.setBorderPainted(false);
        btnCap6.setFocusPainted(false);
        btnCap6.setRequestFocusEnabled(false);
        PanelMenu.add(btnCap6);
        btnCap6.setBounds(10, 420, 200, 40);

        btnCap7.setBackground(new java.awt.Color(255, 255, 255));
        btnCap7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCap7.setText("CAPÍTULO 7");
        btnCap7.setBorder(null);
        btnCap7.setBorderPainted(false);
        btnCap7.setFocusPainted(false);
        btnCap7.setRequestFocusEnabled(false);
        PanelMenu.add(btnCap7);
        btnCap7.setBounds(10, 470, 200, 40);

        btnCap8.setBackground(new java.awt.Color(255, 255, 255));
        btnCap8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCap8.setText("CAPÍTULO 8");
        btnCap8.setBorder(null);
        btnCap8.setBorderPainted(false);
        btnCap8.setFocusPainted(false);
        btnCap8.setRequestFocusEnabled(false);
        PanelMenu.add(btnCap8);
        btnCap8.setBounds(10, 170, 200, 40);

        btnCap9.setBackground(new java.awt.Color(255, 255, 255));
        btnCap9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCap9.setText("CAPÍTULO 9");
        btnCap9.setBorder(null);
        btnCap9.setBorderPainted(false);
        btnCap9.setFocusPainted(false);
        btnCap9.setRequestFocusEnabled(false);
        PanelMenu.add(btnCap9);
        btnCap9.setBounds(10, 220, 200, 40);

        btnCap10.setBackground(new java.awt.Color(255, 255, 255));
        btnCap10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCap10.setText("CAPÍTULO 10");
        btnCap10.setBorder(null);
        btnCap10.setBorderPainted(false);
        btnCap10.setFocusPainted(false);
        btnCap10.setRequestFocusEnabled(false);
        PanelMenu.add(btnCap10);
        btnCap10.setBounds(10, 270, 200, 40);

        btnRegresar.setText("REGRESAR");
        btnRegresar.setBorderPainted(false);
        PanelMenu.add(btnRegresar);
        btnRegresar.setBounds(30, 520, 160, 30);

        getContentPane().add(PanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 220, 570));

        PanelDeslice.setBackground(new java.awt.Color(29, 29, 27));
        PanelDeslice.setPreferredSize(new java.awt.Dimension(220, 50));

        labelUser.setFont(new java.awt.Font("Dotum", 1, 14)); // NOI18N
        labelUser.setForeground(new java.awt.Color(255, 255, 255));
        labelUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PanelDesliceLayout = new javax.swing.GroupLayout(PanelDeslice);
        PanelDeslice.setLayout(PanelDesliceLayout);
        PanelDesliceLayout.setHorizontalGroup(
            PanelDesliceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelUser, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        PanelDesliceLayout.setVerticalGroup(
            PanelDesliceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelUser, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(PanelDeslice, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        PanelHistorial.setBackground(new java.awt.Color(0, 0, 0));
        PanelHistorial.setLayout(null);

        btnCerrarHistorial.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrarHistorial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCerrarHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue_exit_delete_delete_12417.png"))); // NOI18N
        btnCerrarHistorial.setBorder(null);
        btnCerrarHistorial.setBorderPainted(false);
        btnCerrarHistorial.setFocusPainted(false);
        btnCerrarHistorial.setOpaque(true);
        btnCerrarHistorial.setRequestFocusEnabled(false);
        PanelHistorial.add(btnCerrarHistorial);
        btnCerrarHistorial.setBounds(40, 40, 50, 50);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("HISTORIAL USUARIO");
        PanelHistorial.add(jLabel9);
        jLabel9.setBounds(0, 0, 770, 80);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notas.png"))); // NOI18N
        PanelHistorial.add(jLabel10);
        jLabel10.setBounds(490, 10, 100, 60);

        tablaUserHistorial.setBackground(new java.awt.Color(255, 255, 255));
        tablaUserHistorial.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tablaUserHistorial.setForeground(new java.awt.Color(0, 0, 0));
        tablaUserHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaUserHistorial.setFocusable(false);
        tablaUserHistorial.setSelectionBackground(new java.awt.Color(0, 153, 255));
        tablaUserHistorial.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tablaUserHistorial.getTableHeader().setResizingAllowed(false);
        tablaUserHistorial.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaUserHistorial);

        PanelHistorial.add(jScrollPane2);
        jScrollPane2.setBounds(40, 110, 690, 380);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/his.jpg"))); // NOI18N
        PanelHistorial.add(jLabel12);
        jLabel12.setBounds(0, 0, 770, 620);

        getContentPane().add(PanelHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 770, 620));

        PanelPreguntas.setBackground(new java.awt.Color(184, 207, 229));
        PanelPreguntas.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        PanelPreguntas.setMinimumSize(new java.awt.Dimension(440, 460));
        PanelPreguntas.setPreferredSize(new java.awt.Dimension(720, 530));
        PanelPreguntas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SubPanel.setMinimumSize(new java.awt.Dimension(75, 28));
        SubPanel.setPreferredSize(new java.awt.Dimension(75, 28));

        IniciarPregunta.setLayout(null);

        numeroPregunta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        IniciarPregunta.add(numeroPregunta);
        numeroPregunta.setBounds(10, 20, 110, 30);

        Pregunta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        IniciarPregunta.add(Pregunta);
        Pregunta.setBounds(140, 0, 510, 70);

        PanelRecuerda.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        PanelRecuerda.setMinimumSize(new java.awt.Dimension(610, 270));
        PanelRecuerda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Recuerda.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Recuerda.setForeground(new java.awt.Color(255, 255, 255));
        Recuerda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/focus2.png"))); // NOI18N
        PanelRecuerda.add(Recuerda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 550, 120));

        txtRespuesta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelRecuerda.add(txtRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 293, 39));

        btnAceptarPizarra.setText("ACEPTAR");
        PanelRecuerda.add(btnAceptarPizarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 142, 33));

        sumNota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelRecuerda.add(sumNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 180, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pizza.jpg"))); // NOI18N
        PanelRecuerda.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 270));

        IniciarPregunta.add(PanelRecuerda);
        PanelRecuerda.setBounds(40, 80, 610, 270);

        PanelOpciones.setMinimumSize(new java.awt.Dimension(670, 260));
        PanelOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Figura 1.jpg"))); // NOI18N
        PanelOpciones.add(imagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, 140));

        imagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Figura 2.jpg"))); // NOI18N
        PanelOpciones.add(imagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        RadioButtomGroup.add(respuesta1);
        respuesta1.setBorder(null);
        respuesta1.setFocusPainted(false);
        respuesta1.setRequestFocusEnabled(false);
        PanelOpciones.add(respuesta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 36, 630, 40));

        RadioButtomGroup.add(respuesta2);
        respuesta2.setBorder(null);
        respuesta2.setFocusPainted(false);
        respuesta2.setRequestFocusEnabled(false);
        PanelOpciones.add(respuesta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 86, 634, 37));

        RadioButtomGroup.add(respuesta3);
        respuesta3.setBorder(null);
        respuesta3.setFocusPainted(false);
        respuesta3.setRequestFocusEnabled(false);
        PanelOpciones.add(respuesta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 132, 630, 40));

        RadioButtomGroup.add(respuesta4);
        respuesta4.setBorder(null);
        respuesta4.setFocusPainted(false);
        respuesta4.setRequestFocusEnabled(false);
        PanelOpciones.add(respuesta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 182, 630, 40));

        IniciarPregunta.add(PanelOpciones);
        PanelOpciones.setBounds(10, 80, 670, 260);

        btnNextPregunta.setBackground(new java.awt.Color(0, 0, 0));
        btnNextPregunta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNextPregunta.setForeground(new java.awt.Color(255, 255, 255));
        btnNextPregunta.setText("NEXT");
        btnNextPregunta.setBorder(null);
        btnNextPregunta.setEnabled(false);
        btnNextPregunta.setPreferredSize(new java.awt.Dimension(81, 31));
        IniciarPregunta.add(btnNextPregunta);
        btnNextPregunta.setBounds(480, 380, 170, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/registerB.jpg"))); // NOI18N
        IniciarPregunta.add(jLabel5);
        jLabel5.setBounds(0, 350, 700, 80);
        IniciarPregunta.add(Incorrecta);
        Incorrecta.setBounds(520, 60, 120, 20);
        IniciarPregunta.add(Correcta);
        Correcta.setBounds(390, 60, 110, 20);

        SubPanel.addTab("PREGUNTAS", IniciarPregunta);

        PanelPreguntas.add(SubPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 700, 460));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/education.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(74, 75));
        jLabel3.setMinimumSize(new java.awt.Dimension(74, 75));
        jLabel3.setPreferredSize(new java.awt.Dimension(74, 75));
        PanelPreguntas.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 70, 70));

        tituloCap.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tituloCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book-bookmark-icon_34486.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloCap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloCap, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        PanelPreguntas.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 580, 70));

        getContentPane().add(PanelPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 740, 560));

        PanelBotonesIndice.setPreferredSize(new java.awt.Dimension(0, 0));

        btnIndice.setText("ÍNDICE");
        btnIndice.setBorder(null);
        btnIndice.setBorderPainted(false);
        btnIndice.setFocusPainted(false);
        btnIndice.setRequestFocusEnabled(false);

        btnAleatorio.setText("TEST ALEATORIO");
        btnAleatorio.setBorder(null);
        btnAleatorio.setBorderPainted(false);
        btnAleatorio.setFocusPainted(false);
        btnAleatorio.setRequestFocusEnabled(false);

        btnSalir.setText("SALIR");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setFocusPainted(false);
        btnSalir.setRequestFocusEnabled(false);

        btnHistorial.setText("HISTORIAL");
        btnHistorial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHistorial.setBorderPainted(false);
        btnHistorial.setFocusPainted(false);
        btnHistorial.setRequestFocusEnabled(false);

        javax.swing.GroupLayout PanelBotonesIndiceLayout = new javax.swing.GroupLayout(PanelBotonesIndice);
        PanelBotonesIndice.setLayout(PanelBotonesIndiceLayout);
        PanelBotonesIndiceLayout.setHorizontalGroup(
            PanelBotonesIndiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesIndiceLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(PanelBotonesIndiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAleatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIndice, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        PanelBotonesIndiceLayout.setVerticalGroup(
            PanelBotonesIndiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesIndiceLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnIndice, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAleatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(PanelBotonesIndice, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 230, 240));

        FondoTotal.setMinimumSize(new java.awt.Dimension(1000, 625));
        FondoTotal.setPreferredSize(new java.awt.Dimension(1000, 620));
        FondoTotal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/libro.jpg"))); // NOI18N
        FondoTotal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 220, 570));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MENÚ PRINCIPAL");
        FondoTotal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 780, 120));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/redesImg.jpg"))); // NOI18N
        FondoTotal.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 620));

        getContentPane().add(FondoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

        setSize(new java.awt.Dimension(1004, 653));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQuestions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Correcta;
    public javax.swing.JPanel FondoTotal;
    public javax.swing.JLabel Incorrecta;
    public javax.swing.JPanel IniciarPregunta;
    public javax.swing.JPanel PanelBotonesIndice;
    public javax.swing.JPanel PanelDeslice;
    public javax.swing.JPanel PanelHistorial;
    public javax.swing.JPanel PanelMenu;
    public static javax.swing.JPanel PanelOpciones;
    public javax.swing.JPanel PanelPreguntas;
    public javax.swing.JPanel PanelRecuerda;
    public static javax.swing.JLabel Pregunta;
    public static javax.swing.ButtonGroup RadioButtomGroup;
    public static javax.swing.JLabel Recuerda;
    public javax.swing.JTabbedPane SubPanel;
    private javax.swing.JLabel background;
    public static javax.swing.JButton btnAceptarPizarra;
    public static javax.swing.JButton btnAleatorio;
    public static javax.swing.JButton btnCap1;
    public static javax.swing.JButton btnCap10;
    public static javax.swing.JButton btnCap2;
    public static javax.swing.JButton btnCap3;
    public static javax.swing.JButton btnCap4;
    public static javax.swing.JButton btnCap5;
    public static javax.swing.JButton btnCap6;
    public static javax.swing.JButton btnCap7;
    public static javax.swing.JButton btnCap8;
    public static javax.swing.JButton btnCap9;
    public static javax.swing.JButton btnCerrarHistorial;
    public static javax.swing.JButton btnHistorial;
    public static javax.swing.JButton btnIndice;
    public static javax.swing.JButton btnNext;
    public static javax.swing.JButton btnNextPregunta;
    public static javax.swing.JButton btnRegresar;
    public static javax.swing.JButton btnSalir;
    public javax.swing.JLabel imagen1;
    public javax.swing.JLabel imagen2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel labelUser;
    public static javax.swing.JLabel numeroPregunta;
    public static javax.swing.JRadioButton respuesta1;
    public static javax.swing.JRadioButton respuesta2;
    public static javax.swing.JRadioButton respuesta3;
    public static javax.swing.JRadioButton respuesta4;
    public static javax.swing.JLabel sumNota;
    public final javax.swing.JTable tablaUserHistorial = new javax.swing.JTable();
    public static javax.swing.JLabel tituloCap;
    public static javax.swing.JLabel txtRespuesta;
    // End of variables declaration//GEN-END:variables
}
